broker: # default as localhost:port , customization can be added in future releases
exchange:
  name: scaleworks
  type: topic  # default as topic, customization can be added in future releases
  durable: true # default as true, customization can be added in future releases
jobs:
  sync_nodes:
    interval: 3m
    routing_key: sync_nodes
<<<<<<< HEAD
    command_template:  {"job_name": "sync_nodes", "when_distributed": Time.now} 
=======
    command_template: # hard coded as {"job_name": "sync_nodes", "when_distributed": Time.now}, customization can be added in future releases
>>>>>>> 697fa299018f9db9e5341aab4bceb78793642bf2
  sync_clouds:
    interval: 1d
    routing_key: sync_nodes
